feat: Loading UX 개선
kimjh96/cocstorage-client-mobile pull request #2
Opened 2022-10-03 12:31 UTC by insd47

뒤로가기 시 캐싱된 데이터 사용은 검토가 필요할 수 있음.

2022-10-06 13:52 UTC, kimjh96 requested changes

2022-10-06 13:52 UTC, kimjh96 commented on src/components/UI/organisms/DummyLoader/index.tsx
> +  const serverSidePagesList = [
`serverSidePages` 요렇게만 네이밍해도 될 것 같아요!

2022-10-06 13:52 UTC, kimjh96 commented on src/components/UI/organisms/DummyLoader/index.tsx
> +      background-position: 0% 0%;
%는 없어도 될 것 같아요.

2022-10-06 13:54 UTC, kimjh96 commented
https://user-images.githubusercontent.com/64636159/194331085-33c40ac7-60b6-4d08-85af-24966ca4f162.MP4

아이폰 사파리 환경 뒤로가기 시 동작이 이상한 부분이 있어요.
홈 - 게시판 - 게시글 상세 진입 후 뒤로가기 시 게시판 페이지가 놔와야 하는데 홈이 나오네요.

2022-10-08 09:32 UTC, insd47 commented
> RPReplay_Final1665062230.MP4 
> 아이폰 사파리 환경 뒤로가기 시 동작이 이상한 부분이 있어요. 홈 - 게시판 - 게시글 상세 진입 후 뒤로가기 시 게시판 페이지가 나와야 하는데 홈이 나오네요.

테스트 서버에서 제 아이패드로 테스트하여 보았는데, 해당 문제가 발생하지 않았습니다. 환경은 iPadOS 16.1 Developer Beta 11입니다.
더 이상 아이폰을 사용하지 않아서 해당 기기로 테스트를 진행할 수 없는 점 양해 부탁드립니다.

2022-10-08 09:37 UTC, insd47 commented
+ 뒤로가기 관련 기능 제거' 로 헤더를 작성하여 혼선이 조금 있을 수도 있어서 코멘트 남깁니다.
'뒤로가기 시 캐싱된 데이터 사용' 이 아닌,
'뒤로가기 시 스켈레톤 표시' 관련 기능이 제거된 것입니다.

2022-10-10 05:39 UTC, kimjh96 commented
> > RPReplay_Final1665062230.MP4
> > 아이폰 사파리 환경 뒤로가기 시 동작이 이상한 부분이 있어요. 홈 - 게시판 - 게시글 상세 진입 후 뒤로가기 시 게시판 페이지가 나와야 하는데 홈이 나오네요.
> 
> 테스트 서버에서 제 아이패드로 테스트하여 보았는데, 해당 문제가 발생하지 않았습니다. 환경은 iPadOS 16.1 Developer Beta 11입니다. 더 이상 아이폰을 사용하지 않아서 해당 기기로 테스트를 진행할 수 없는 점 양해 부탁드립니다.

음

2022-10-10 05:46 UTC, merged

2022-10-10 06:36 UTC, kimjh96 reviewed
고생하셨습니다!